main: com.retrontology.prizes.Prizes
name: Prizes
version: 0.1.1
author: Retrontology
description: A system for distribution of prizes
permissions: 
  prizes.citizen:
    description: Required for redeeming prizes
    default: false
  prizes.admin:
    description: Required for server admin commands such as reset, update, etc
    default: false
commands:
  prizes:
    description: A system for distribution of prizes
    aliases: [prizes] 
    permission: prizes.citizen
    permission-message: Become a citizen to access the prize system
    usage: |
      /prizes check - Check to see if you have any prizes
      /prizes claim - Claim your prizes (if any)
  prizes check:
    description: Check to see what prizes you have
    aliases: [prize view]
    permission: prizes.citizen
    permission-message: Become a citizen to access the prize system
    usage: |
      /prizes check
  prizes claim:
    description: Claim your prize (if you have one)
    aliases: [prize get]
    permission: prizes.citizen
    permission-message: Become a citizen to access the prize system
    usage: |
      /prizes claim
